name: Build and Test Puzzles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Build all puzzles
      run: make

    - name: Run tests for all puzzles
      run: make test

    - name: Clean up
      run: make clean